[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[window]
padding = { x = 4, y = 7 }
dynamic_padding = true
decorations = "full"
blur = true
opacity = 0.97
dimensions = { columns = 110, lines = 28 }
startup_mode = "Windowed"

[env]
term = "xterm-256color"

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
size = 18.0

[colors.primary]
background = '#1d2021'
foreground = '#cccccc'

[colors.normal]
black   = '#282828'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[cursor]

style = { shape = "Beam", blinking = "On" }

